"""Display labels only. Machine enums remain unchanged in exports and rules."""
LABELS = {
    "hook": "开场吸引", "setup": "建立情境", "context": "交代背景", "explanation": "解释说明",
    "claim": "提出观点", "evidence": "展示证据", "personal_reflection": "个人反思",
    "emotional_statement": "表达感受", "conflict": "呈现矛盾", "escalation": "推进变化",
    "turning_point": "叙事转折", "reveal": "揭示信息", "comparison": "对比", "transition": "过渡",
    "summary": "总结", "callback": "呼应前文", "payoff": "回应铺垫", "ending": "结尾", "audio_cue": "声音提示",
    "KEEP_A_ROLL": "保留人物口播", "A-roll": "人物口播", "B-roll": "补充画面",
    "EVIDENCE": "展示证据", "ILLUSTRATION": "辅助说明", "ESTABLISH": "建立空间", "CONTEXT": "交代背景",
    "ACTION": "展示动作", "PROCESS": "展示过程", "DETAIL": "展示细节", "REACTION": "人物反应",
    "EMOTION": "表达情绪", "ATMOSPHERE": "营造氛围", "RELATIONSHIP": "交代关系", "CONTRAST": "形成对比",
    "REVEAL": "揭示变化", "METAPHOR": "隐喻", "TRANSITION": "过渡", "BREATHING": "环境与留白",
    "PAYOFF": "回应铺垫", "CALLBACK": "呼应前文", "ARCHIVAL_EVIDENCE": "历史资料证据", "SOFTWARE_EVIDENCE": "软件操作证据",
    "PASS": "基本匹配", "SOFT_GATE": "部分匹配，需复核", "HARD_GATE": "不作推荐", "UNKNOWN": "证据不足，未确定",
    "PERSON": "人物", "PERSON_REACTION": "人物反应", "OBJECT": "物体", "ENVIRONMENT": "环境",
    "ENVIRONMENT_STATE": "环境状态", "LOCATION_ESTABLISHING": "空间位置", "RESULT": "结果", "AFTERMATH": "事后状态",
    "ABSTRACT_REFLECTION": "抽象反思", "SOUND_LED": "声音主导", "OTHER": "其他", "MIXED": "多个主体",
    "NEEDS_HUMAN_REVIEW": "需要人工判断", "DIRECTLY_VISUALIZABLE": "可直接用画面表达",
    "PARTIALLY_VISUALIZABLE": "只能用画面表达一部分", "GAP": "素材缺口", "SOUND_INSTRUCTION": "声音指令",
    "HIGH": "高", "MEDIUM": "中", "LOW": "低", "NONE": "无", "SAME_SUBJECT_STATE_CHANGE": "同一主体的状态变化",
    "STATE_TRANSITION": "状态变化", "READY": "可按表查找", "SOURCE_REVIEW": "需回看原片", "RESHOOT_PRIORITY": "优先补拍",
    "EXACT_OR_CONTAINED": "原句匹配", "FUZZY_SEQUENCE": "近似语句匹配", "DOCUMENT_CONTEXT_ALIGNMENT": "全文顺序辅助匹配",
    "SUPPORTED": "有证据支持", "PARTIAL": "部分支持", "UNSUPPORTED": "缺少证据",
    "DIRECT": "可直接用画面表达", "KEEP_A_ROLL_PREFERRED": "更适合人物口播", "HUMAN_REVIEW": "需要人工判断",
    "NEED_SOURCE_REVIEW": "需回看原片", "SUBJECT_MISMATCH": "主体不匹配", "FACT_CONFLICT": "事实冲突",
    "SEMANTIC_ONLY": "只在文字上相关", "UNSUPPORTED_CLAIM": "不能证明文稿判断", "SHOT_ROLE_MISMATCH": "镜头用途不符",
}
